// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urdbbrndqpbhxjfpeafd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZGJicm5kcXBiaHhqZnBlYWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDI5MzcsImV4cCI6MjA2NjM3ODkzN30.wK3jo0v4Ez1gAfEjxSpnXQ6FQG0LFmRW_2mC3yPK-ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);